version: "3"
services:
  recommender:
    image: ''
    ports:
      - 5000:80 
    networks:
      - backend
    depends_on:
      - redis
      - db
    deploy:
      replicas: 2
      update_conifg:
        parallelism: 2
      restart_policy:
        condition: on-failure

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - backend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  db:
    image: postgres:9.6
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  backend:

volumes:
  db-data:




